<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list"
    id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
    style="display: none;">
    <li>
        <?php
        $cards = $block->getAvailableCcTypes();

        $oneCard = count($cards) === 1;
        $first = true;

        foreach ($cards as $code => $label) {
            if ($oneCard) { ?>
                <input type="hidden"
                       id="payzen_gift_cc_type_<?php echo $block->escapeHtml($code); ?>"
                       value="<?php echo $block->escapeHtml($code); ?>"
                       name="payment[payzen_gift_cc_type]" />
            <?php } else { ?>
                <input class="radio"
                       type="radio"
                       <?php if ($first) { ?> checked="checked"<?php } ?>
                       id="payzen_gift_cc_type_<?php echo $block->escapeHtml($code); ?>"
                       value="<?php echo $block->escapeHtml($code); ?>"
                       name="payment[payzen_gift_cc_type]" />
            <?php
                $first = false;
            }
            ?>

            <label for="payzen_gift_cc_type_<?php echo $block->escapeHtml($code); ?>" style="float: none;">
                <img alt="<?php echo $block->escapeHtml($label); ?>"
                     src="<?php echo $block->escapeHtml($block->getCcTypeImageSrc($code)); ?>"
                     title="<?php echo $block->escapeHtml($label); ?>" />
            </label>
            <br style="margin-bottom: 5px;" />
        <?php } ?>
    </li>
</ul>