<?php
/**
 * PayZen V2-Payment Module version 2.1.3 for Magento 2.x. Support contact : support@payzen.eu.
 *
 * NOTICE OF LICENSE
 *
 * This source file is licensed under the Open Software License version 3.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @author    Lyra Network (http://www.lyra-network.com/)
 * @copyright 2014-2017 Lyra Network and contributors
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @category  payment
 * @package   payzen
 */
?>

<table>
    <tbody>
        <tr>
            <td style="vertical-align: middle; padding-right: 0;">
                <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('Lyranetwork_Payzen::images/loading.gif')); ?>">
            </td>
            <td style="vertical-align: middle; padding-left: 0;">
                <span style="font-weight: bold;">
                <?php
                $fields = $block->getFormFields();

                if ($fields['vads_action_mode'] === 'SILENT') {
                    echo $block->escapeHtml(__('Please wait a moment. Your order payment is now processing.'));
                } else {
                    echo $block->escapeHtml(__('Please wait a moment. This page will transfer your data to PayZen payment platform in a few seconds.'));
                }
                ?>
                </span><br />
                <span><?php echo $block->escapeHtml(__('If nothing happens in 10 seconds, click the button below.')); ?></span>
            </td>
        </tr>
    </tbody>
</table>

<div class="actions">
    <button class="action primary redirect" title="<?php echo $block->escapeHtml(__('Send')); ?>" type="submit">
        <span><?php echo $block->escapeHtml(__('Send')); ?></span>
    </button>
</div>