<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<table>
    <tbody>
        <tr>
            <td style="vertical-align: middle; padding-right: 0;">
                <img src="<?php echo $block->escapeUrl($block->getViewFileUrl('Lyranetwork_Payzen::images/loading.gif')); ?>">
            </td>
            <td style="vertical-align: middle; padding-left: 0;">
                <span style="font-weight: bold;">
                <?php
                echo $block->escapeHtml(__('Please wait a moment. This page will transfer your data to PayZen payment gateway in a few seconds.'));
                ?>
                </span><br />
                <span><?php echo $block->escapeHtml(__('If nothing happens in 10 seconds, click the button below.')); ?></span>
            </td>
        </tr>
    </tbody>
</table>

<div class="actions">
    <button class="action primary redirect" title="<?php echo $block->escapeHtml(__('Send')); ?>" type="submit" id="payzen_payment_form_btn">
        <span><?php echo $block->escapeHtml(__('Send')); ?></span>
    </button>
</div>