<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list"
    id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
    style="display: none;">
    <li>
        <?php
        $options = $block->getAvailableOptions();

        $oneOption = count($options) === 1;
        $first = true;

        foreach ($options as $key => $option) {
            if ($oneOption) { ?>
                <input type="hidden"
                       id="option_<?php echo $block->escapeHtml($key); ?>"
                       value="<?php echo $block->escapeHtml($key); ?>"
                       name="payment[payzen_oney_option]" />
            <?php } else { ?>
                <input class="radio"
                       type="radio"
                       <?php if ($first) { ?> checked="checked"<?php } ?>
                       id="option_<?php echo $block->escapeHtml($key); ?>"
                       value="<?php echo $block->escapeHtml($key); ?>"
                       name="payment[payzen_oney_option]" />
            <?php
                $first = false;
            }
            ?>

            <label style="float: none;"><?php echo $block->escapeHtml($option['label']); ?></label>
            <br style="margin-bottom: 5px;" />
        <?php } ?>
    </li>
</ul>