<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
$cards = $block->getAvailableMeans();

if ($block->regroupPaymentMeans()) :
?>

<ul class="form-list"
    id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
    style="display: none;">
<?php
    $single = count($cards) === 1;

    // Show card logos as radio buttons.
    $first = true;
    $html = '';
    foreach ($cards as $card) {
        $code  = $card['value'];
        $label = $card['label'];
        $html .= '<div class="payzen-card">';

        if ($single) {
            $html .= '<input type="hidden" id="payzen_other_cc_type_' . $block->escapeHtml($code)
                . '" value="' . $block->escapeHtml($code) . '" name="payment[payzen_other_cc_type]" />' ;
        } else {
            $html .= '<input type="radio" class="radio" id="payzen_other_cc_type_' . $block->escapeHtml($code)
                . '"' . ($first ? ' checked="checked"' : '') . ' value="'
                . $block->escapeHtml($code) . '" name="payment[payzen_other_cc_type]" />' ;
        }

        $first = false;
        $ccImageSrc = $block->getCcTypeImageSrc($code);
        
        $label = $ccImageSrc ? '<img alt="' . $block->escapeHtml($label) . '"
                                     src="' . $block->escapeHtml($ccImageSrc) . '"
                                     title="' . $block->escapeHtml($label) . '" />'
                : "<span>" . $block->escapeHtml($label) . "</span>";
        
        $html .= '<label for="payzen_other_cc_type_' . $block->escapeHtml($code) . '">'
                    . $label . 
                  '</label>';
        $html .= '</div>';
    }

    echo '<li>' . $html . '</li>';
?>
</ul>

<?php
else:
    foreach ($cards as $card) {
    ?>
        <ul class="form-list"
            id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>_<?php echo $card['code']; ?>"
            style="display: none;">
        </ul>
    <?php
    }
endif;
?>