<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$oneClickActive = $block->getConfigData('oneclick_active'); // 1-Click enabled ?
$customer = $block->getCurrentCustomer(); // Logged in customer.
?>

<ul class="form-list"
    id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
    style="display:none;">
<?php
if ($block->isLocalCcType()) :
    $cards = $block->getAvailableCcTypes();
    $single = count($cards) === 1;

    // Show card logos as radio buttons.
    $amexCards = '';
    $cbCards = '';
    $otherCards = '';

    $first = true;
    foreach ($cards as $code => $label) {
        $html = '<div class="payzen-card">';

        if ($single) {
            $html .= '<input type="hidden" id="payzen_standard_cc_type_' . $block->escapeHtml($code)
                . '" value="' . $block->escapeHtml($code) . '" name="payment[payzen_standard_cc_type]"/>' ;
        } else {
            $html .= '<input type="radio" class="radio" id="payzen_standard_cc_type_' . $block->escapeHtml($code)
                . '"' . ($first ? ' checked="checked"' : '') . ' value="'
                . $block->escapeHtml($code) . '" name="payment[payzen_standard_cc_type]"/>' ;
        }

        $first = false;

        $html .= '<label for="payzen_standard_cc_type_' . $block->escapeHtml($code) . '">
                    <img alt="' . $block->escapeHtml($label) . '"
                         src="' . $block->escapeHtml($block->getCcTypeImageSrc($code)) . '"
                         title="' . $block->escapeHtml($label) . '" />
                  </label>';
        $html .= '</div>';

        $network = $block->getCcTypeNetwork($code);
        if ($network === 'AMEX') {
            $amexCards .= $html;
        } elseif ($network === 'CB') {
            $cbCards .= $html;
        } else {
            $otherCards .= $html;
        }
    }

    if ($cbCards != '') {
        echo '<li class="payzen-standard-cc-block">' . $cbCards . '</li>';
    }
    if ($amexCards != '') {
        echo '<li class="payzen-standard-cc-block">' . $amexCards . '</li>';
    }
    if ($otherCards != '') {
        echo '<li class="payzen-standard-cc-block">' . $otherCards . '</li>';
    }
endif;

if ($oneClickActive && $customer && $customer->getCustomAttribute('payzen_identifier')) : ?>
        <li class="payzen-standard-cc-block">
            <?php echo $block->escapeHtml(__('You will enter payment data after order confirmation.')); ?>
        </li>
        <li class="payzen-standard-cc-block">
            <span class="or"><?php echo $block->escapeHtml(__('OR')); ?></span>
        </li>

        <li class="payzen-standard-cc-block">
            <a class="payzen-payment-link" href="javascript: void(0);"
                onclick="javascript: payzenUpdatePaymentBlock('id');">
                <?php echo $block->escapeHtml(__('Click here to pay with your registered means of payment.')); ?>
            </a>
        </li>

        <!-- Payment with registered card block. -->
        <li class="payzen-standard-id-block">
            <input type="hidden" value="1" name="payment[payzen_standard_use_identifier]" />
            <span>
                <?php echo $block->escapeHtml(__('You will pay with your registered means of payment %s. No data entry is needed.')); ?>
            </span>
        </li>

        <li class="payzen-standard-id-block">
            <span class="or"><?php echo $block->escapeHtml(__('OR')); ?></span>
        </li>

        <li class="payzen-standard-id-block">
            <a class="payzen-payment-link" href="javascript: void(0);"
                onclick="javascript: payzenUpdatePaymentBlock('cc');">
                <?php echo $block->escapeHtml(__('Click here to pay with another means of payment.')); ?>
            </a>
        </li>
<?php endif; ?>
</ul>

<?php if ($oneClickActive && $customer && $customer->getCustomAttribute('payzen_identifier')) : ?>
<script>
    require([
        'prototype'
    ], function() {
        // Display payment by identifier block when standard payment is selected.
        Event.stopObserving('p_method_payzen_standard', 'click', onMethodPayzenStandardClick);
        Event.observe('p_method_payzen_standard', 'click', onMethodPayzenStandardClick);

        payzenUpdatePaymentBlock.delay(0.2, 'id');
    });
</script>
<?php endif;?>