<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none; margin-left: 15px;">
    <li>
        <?php
        $options = $this->getAvailableOptions();
        if (count($options) === 1) {
            $keys = array_keys($options);

            $key = $keys[0]; // The option key in options array.
            $option = $options[$key]; // The option.
            echo '<input type="hidden" id="option' . $key . '" value="' . $key . '" name="payment[payzen_multi_option]" disabled=""/>
                  <label style="float: none;">' . $option['label'] . '</label> <br style="margin-bottom: 5px;"/>';
        } else {
            $first = true;
            foreach ($options as $key => $option) {
                echo '<input class="radio" type="radio"'. ($first ? ' checked="checked"' : '') . ' id="option' . $key . '" value="' . $key . '" name="payment[payzen_multi_option]" disabled=""/>
                      <label style="float: none;" for="option' . $key . '">' . $option['label'] . '</label> <br style="margin-bottom: 5px;"/>';
                $first = false;
            }
        }
        ?>
    </li>
</ul>