<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<form id="payzen_payment_form" method="POST" action="<?php echo $this->getFormAction();?>"  method="POST">
    <?php foreach ($this->getFormFields() as $key=>$value) :?>
        <input type="hidden" name="<?php echo $key;?>" value="<?php echo $value;?>">
    <?php endforeach;?>

    <table>
        <tbody>
            <tr>
                <td style="vertical-align: middle;">
                    <img style="margin-right: 8px;" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'payzen/loading.gif' ?>">
                </td>
                <td style="vertical-align: middle;">
                    <span style="font-weight: bold;"><?php echo Mage::helper('payzen')->__('Please wait a moment. This page will transfer your data to PayZen payment gateway in a few seconds.'); ?></span><br />
                    <span><?php echo Mage::helper('payzen')->__('If nothing happens in 10 seconds, click the button below.');?></span>
                </td>
            </tr>

            <tr>
                <td colspan="2">
                    <div style="border-top: 1px solid #E4E4E4; clear: both; margin: 4em 0 0; padding: 8px 0 0; text-align: right;">
                        <button class="scalable save" title="<?php echo Mage::helper('payzen')->__('Send');?>" type="submit">
                            <span><span><?php echo Mage::helper('payzen')->__('Send');?></span></span>
                        </button>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</form>

<script type="text/javascript">
//<![CDATA[
    var redirect = new varienForm('payzen_payment_form', '');
    Event.observe(window, 'load', function() {
        redirect.submit();
    });
//]]>
</script>