<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
//<![CDATA[

    Translator.add(
            'Incorrect credit card number.',
            "<?php echo Mage::helper('payzen')->__('Incorrect credit card number.') ?>"
    );
    Translator.add(
            'Incorrect credit card CVV.',
            "<?php echo Mage::helper('payzen')->__('Incorrect credit card CVV.') ?>"
    );
    Translator.add(
            'Incorrect credit card expiration date.',
            "<?php echo Mage::helper('payzen')->__('Incorrect credit card expiration date.') ?>"
    );

    Validation.addAllThese([
            ['validate-payzen-standard-cc-exp', 'Incorrect credit card expiration date.', function(v, elm) {
                    var ccExpYear = v;
                    var ccExpMonth = $('payzen_standard_cc_exp_month').value;
                    var currentTime = new Date();
                    var currentMonth = currentTime.getMonth() + 1;
                    var currentYear = currentTime.getFullYear();
                    if (ccExpMonth < currentMonth && ccExpYear == currentYear) {
                        return false;
                    }
                    return true;
            }],
            ['validate-payzen-standard-cc-number', 'Incorrect credit card number.', function(v) {
                return /^\d{13,19}$/.test(v);
            }],
            ['validate-payzen-standard-cc-cvv', 'Incorrect credit card CVV.', function(v) {
                return /^\d{3,4}$/.test(v);
            }]
    ]);

//]]>
</script>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none;">
<?php
if (Mage::helper('payzen')->isCurrentlySecure()) : // Admin backend secured, use ws payment.
    $cards = $this->getAvailableManualCcTypes();

    // Show card logos as radio buttons.
    $amexCards = '';
    $cbCards = '';
    $otherCards = '';

    $count = count($cards);

    $first = true;
    foreach ($cards as $code => $label) {
        $html = '<div class="payzen-card">';

        if ($count == 1) {
            $html .= '<input type="hidden" id="payzen_standard_cc_type_' . $code . '" value="' . $code . '" name="payment[payzen_standard_cc_type]"/>' ;
        } else {
            $html .= '<input type="radio" class="radio" id="payzen_standard_cc_type_' . $code . '"' . ($first ? ' checked="checked"' : '') . ' value="' . $code . '" name="payment[payzen_standard_cc_type]"/>' ;
        }

        $first = false;

        $html .= '<label for="payzen_standard_cc_type_' . $code . '">';

        if ($this->getCcTypeImageSrc($code)) {
            $html .= '<img alt="' . $label . '" src="' . $this->getCcTypeImageSrc($code) . '" title="' . $label . '" />';
        } else {
            $html .= '<span>' . $label . '<span/>';
        }

        $html .= '</label></div>';

        $network = $this->getCcTypeNetwork($code);
        if ($network == 'AMEX') {
            $amexCards .= $html;
        } elseif ($network == 'CB') {
            $cbCards .= $html;
        } else {
            $otherCards .= $html;
        }
    }

    echo '<li style="margin-top: 10px;"></li>';
    if ($cbCards != '') echo '<li>' . $cbCards . '</li>';
    if ($amexCards != '') echo '<li>' . $amexCards . '</li>';
    if ($otherCards != '') echo '<li>' . $otherCards . '</li>';
?>

    <li>
        <div class="input-box">
            <label for="payzen_standard_cc_number"><?php echo Mage::helper('payzen')->__('Card Number'); ?> <span class="required">*</span></label><br/>
            <input class="input-text required-entry validate-payzen-standard-cc-number" autocomplete="off" maxlength="19" type="text" name="payment[payzen_standard_cc_number]" id="payzen_standard_cc_number" style="width: 200px;" />
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="payzen_standard_cc_exp_month"><?php echo Mage::helper('payzen')->__('Expiration Date'); ?> <span class="required">*</span></label><br/>
            <select class="month required-entry" name="payment[payzen_standard_cc_exp_month]" id="payzen_standard_cc_exp_month" style="width: 95px;" >
                <?php foreach (range(1, 12) as $month) : ?>
                    <option value="<?php echo $month; ?>"><?php echo str_pad($month, 2, '0', STR_PAD_LEFT); ?></option>
                <?php endforeach; ?>
            </select>
            <select class="year required-entry validate-payzen-standard-cc-exp" name="payment[payzen_standard_cc_exp_year]" id="payzen_standard_cc_exp_year" style="width: 100px;">
                <?php foreach (range(Mage::getSingleton('core/date')->date('Y'), Mage::getSingleton('core/date')->date('Y') + 9) as $year) : ?>
                    <option value="<?php echo $year; ?>"><?php echo $year; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="payzen_standard_cc_cvv"><?php echo Mage::helper('payzen')->__('CVV'); ?> <span class="required">*</span></label><br/>
            <input class="input-text required-entry validate-payzen-standard-cc-cvv" autocomplete="off" maxlength="4" type="text" name="payment[payzen_standard_cc_cvv]" id="payzen_standard_cc_cvv" style="width: 60px;" />
        </div>
    </li>
<?php endif;?>
</ul>