<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<form id="payzen_payment_form" action="<?php echo $block->escapeUrl($block->getFormAction()); ?>" method="POST">
    <?php
    $fields = $block->getFormFields();

    foreach ($fields as $key => $value) :
    ?>
        <input type="hidden"
               name="<?php echo $block->escapeHtml($key); ?>"
               value="<?php echo $block->escapeHtml($value); ?>">
    <?php endforeach; ?>

    <?php echo $block->getChildHtml('redirect_loader'); ?>
</form>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.getElementById("payzen_payment_form").submit();
    });
</script>