<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<button onclick="window.location='<?php echo $block->escapeUrl($block->getButtonUrl()); ?>'; return false;"
        class="scalable"
        type="button">
    <span><?php echo $block->escapeHtml($block->getButtonLabel()); ?></span>
</button>