<?php
/**
 * PayZen V2-Payment Module version 2.1.3 for Magento 2.x. Support contact : support@payzen.eu.
 *
 * NOTICE OF LICENSE
 *
 * This source file is licensed under the Open Software License version 3.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @author    Lyra Network (http://www.lyra-network.com/)
 * @copyright 2014-2017 Lyra Network and contributors
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @category  payment
 * @package   payzen
 */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . $block->getElement()->getId() . '_' . uniqid();
?>

<div class="design_theme_ua_regexp" id="grid<?php echo $block->escapeHtml($_htmlId); ?>">
    <div class="admin__control-table-wrapper">
        <table class="admin__control-table">
            <thead>
            <tr>
                <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                    <th><?php echo $block->escapeHtml($column['label']); ?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tbody id="addRow<?php echo $block->escapeHtml($_htmlId); ?>"></tbody>
        </table>
    </div>
    <input type="hidden" name="<?php echo $block->escapeHtml($block->getElement()->getName()); ?>[__empty]" value="" />

    <script>
        require([
            'mage/template',
            'prototype'
        ], function(mageTemplate) {
            // create row creator
            window.arrayRow<?php echo $block->escapeHtml($_htmlId); ?> = {
                // define row prototypeJS template
                template: mageTemplate(
                    '<tr id="<%- _id %>">'
                    <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                        + '<td<% if (typeof all != "undefined" && all) { %> style="background-color: #b0b0b0;"<% } %>>'
                        + '<?php echo $block->renderCellTemplate($columnName); ?>'
                        + '<\/td>'
                    <?php endforeach; ?>
                    +'<\/tr>'
                ),

                add: function(rowData, insertAfterId) {
                    // generate default template data
                    var templateValues;

                    // prepare template values
                    if (rowData) {
                        templateValues = rowData;
                    } else {
                        var d = new Date();
                        templateValues = {
                            <?php foreach ($block->getColumns() as $columnName => $column) : ?>
                                <?php echo $block->escapeHtml($columnName); ?>: '',
                            <?php endforeach; ?>
                            option_extra_attrs: {},
                            _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                        };
                    }

                    // insert new row after specified row or at the bottom
                    if (insertAfterId) {
                        Element.insert($(insertAfterId), {after: this.template(templateValues)});
                    } else {
                        Element.insert(
                            $('addRow<?php echo $block->escapeHtml($_htmlId); ?>'),
                            {bottom: this.template(templateValues)}
                        );
                    }

                    // fill controls with data
                    if (rowData) {
                        var rowInputElementNames = Object.keys(rowData.column_values);
                        for (var i = 0; i < rowInputElementNames.length; i++) {
                            if ($(rowInputElementNames[i])) {
                                $(rowInputElementNames[i]).value = rowData.column_values[rowInputElementNames[i]];
                            }
                        }
                    }
                }
            };

            // add existing rows
            <?php
            foreach ($block->getArrayRows() as $_rowId => $_row) {
                $id = $block->escapeHtml($_htmlId);
                echo "arrayRow{$id}.add(" . $_row->toJson() . ");\n";
            }
            ?>
        });
    </script>
</div>