<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none;">
    <?php $availCards = $this->getAvailableOptions(); ?>

    <li>
        <div class="payzen-field">
        <?php
        $first = true;
        foreach ($availCards as $key => $option) {
        ?>
            <div class="payzen-card">
            <?php if (count($availCards) === 1) {?>
                <input type="hidden" id="payzen_choozeo_card_type_<?php echo $option['code']; ?>" name="payment[payzen_choozeo_cc_type]" value="<?php echo $option['code']; ?>" disabled="disabled">
            <?php } else { ?>
                <input type="radio" class="radio" id="payzen_choozeo_card_type_<?php echo $option['code']; ?>" name="payment[payzen_choozeo_cc_type]" value="<?php echo $option['code']; ?>"<?php echo ($first ? ' checked="checked"' : ''); ?> disabled="disabled">
            <?php } ?>

                <label for="payzen_choozeo_card_type_<?php echo $option['code']; ?>">
                    <img alt="<?php echo $option['label']; ?>" src="<?php echo $this->getCcTypeImageSrc($option['code']); ?>" title="<?php echo $option['label']; ?>" style="max-height: 40px !important;" />
                </label>

                <?php $first = false; ?>
            </div>
        <?php } ?>
        </div>
    </li>
</ul>