<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none;">
    <?php if (($options = $this->getPaymentOptions()) && is_array($options) && ! empty($options)) : ?>
        <li>
        <?php
        $count = count($options);

        $first = true;
        foreach ($options as $code => $value) {
            $html = '<div class="payzen-option">';

            if ($count == 1) {
                $html .= '<input type="hidden" id="payzen_fullcb_option'.$code.'" value="'.$code.'" name="payment[payzen_fullcb_option]" /><span style="margin-right: 20px;"></span>';
            } else {
                $html .= '<input type="radio"
                                 class="radio"
                                 id="payzen_fullcb_option'.$code.'"'.
                                 ($first ? ' checked="checked"' : '').'
                                 value="'.$code.'"
                                 name="payment[payzen_fullcb_option]"
                                 onclick="javascript: $$(\'.payzen_fullcb_review\').invoke(\'hide\'); $(\'payzen_fullcb_review_'.$value['code'].'\').show();" />' ;
            }

            $html .= '<label for="payzen_fullcb_option'.$code.'">' . $value['label'] . '</label>';
            $html .= '</div>';

            $html .= $this->getHtmlReview($value, $first);
            $html .= '<br style="margin-bottom: 5px;"/>';

            $first = false;

            echo $html;
        }
        ?>
        </li>
    <?php endif; ?>
</ul>
