<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none; margin-left: 15px;">
    <li>
        <?php
        $cards = $this->getAvailableGcTypes();

        // Show card logos as radio buttons.
        $html = '';

        $first = true;
        foreach ($cards as $code => $label) {
            $html .= '<div class="payzen-card">';

            if (count($cards) === 1) {
                $html .= '<input type="hidden" id="payzen_gift_gc_type_'.$code.'" value="'.$code.'" name="payment[payzen_gift_gc_type]" disabled="disabled">' ;
            } else {
                $html .= '<input type="radio" class="radio" id="payzen_gift_gc_type_'.$code.'"'.($first ? ' checked="checked"' : '').' value="'.$code.'" name="payment[payzen_gift_gc_type]" disabled="disabled">' ;
            }

            $first = false;

            $html .= '<label for="payzen_gift_gc_type_'.$code.'">
                          <img alt="'.$label.'" src="'.$this->getGcTypeImageSrc($code).'" title="' . $label . '" />
                      </label>';

            $html .= '</div>';
        }

        echo $html;
        ?>
    </li>
</ul>