<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<p><b>
    <?php echo $this->getMethod()->getTitle(); ?>

    <?php
    $info = $this->getInfo();
    $option = @unserialize($info->getAdditionalData()); // Get chosen payment option if any.

    if (stripos($info->getMethod(), 'payzen_multi') === 0) {
        if (! isset($option) || empty($option)) {
            // Temporary patch for module versions < 1.3 that use additional_information field
            $option = $info->getAdditionalInformation(Lyranetwork_Payzen_Helper_Payment::MULTI_OPTION);
        }

        if (is_array($option) && ! empty($option)) {
            echo '<br />';
            echo $option['label'] . ' (' . $option['count'] . 'X)';
        }
    } elseif ($info->getMethod() === 'payzen_oney') {
        if (is_array($option) && ! empty($option)) {
            echo '<br />';
            echo $option['label'];
        }
    }
    ?>
</b></p>

<?php
if ($info->getCcTransId()) {
    echo Mage::helper('payzen')->__('Transaction ID') . ': ' . $info->getCcTransId();
    echo '<br />';

    if ($info->getCcType() === 'MULTI') {
        echo $this->getTransactionInfoHtml(true);
    } else {
        if (stripos($info->getMethod(), 'payzen_multi') === false) {
            echo Mage::helper('payzen')->__('Transaction UUID') . ': ' . $info->getAdditionalInformation(Lyranetwork_Payzen_Helper_Payment::TRANS_UUID);
            echo '<br />';
        }

        echo Mage::helper('payzen')->__('Means of Payment') . ': ' . $info->getCcType();
    }

    echo '<br />';
}