<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display: none; margin-left: 15px;">
    <li>
        <?php $options = $this->getAvailableOptions(); ?>

        <?php if (count($options) === 1) { ?>
            <label class="payzen-label"><?php echo Mage::helper('payzen')->__('Payment option'); ?></label>
        <?php } else { ?>
            <label class="payzen-label"><?php echo Mage::helper('payzen')->__('Choose your payment option'); ?></label>
        <?php } ?>

        <div class="payzen-field">
        <?php
        if (count($options) === 1) {
            $keys = array_keys($options);

            $key = $keys[0]; // The option key in options array.
            $option = $options[$key]; // The option.
            echo '<input type="hidden" id="option_' . $key . '" value="' . $key . '" name="payment[payzen_multi_option]" disabled="disabled">
                  <label style="float: none;">' . $option['label'] . '</label> <br style="margin-bottom: 5px;" />';
        } else {
            $first = true;
            foreach ($options as $key => $option) {
                echo '<input class="radio" type="radio"'. ($first ? ' checked="checked"' : '') . ' id="option_' . $key . '" value="' . $key . '" name="payment[payzen_multi_option]" disabled="disabled">
                      <label style="float: none;" for="option_' . $key . '">' . $option['label'] . '</label> <br style="margin-bottom: 5px;" />';
                $first = false;
            }
        }
        ?>
        </div>
    </li>

    <?php if ($this->getConfigData('card_info_mode') == 2): ?>
    <?php $availCards = $this->getAvailableCcTypes(); ?>

    <li>
    <?php if (count($availCards) === 1) {?>
        <label class="payzen-label"><?php echo Mage::helper('payzen')->__('Means of payment'); ?></label>
    <?php } else { ?>
        <label class="payzen-label"><?php echo Mage::helper('payzen')->__('Choose your means of payment'); ?></label>
    <?php } ?>

        <div class="payzen-field">
        <?php
        $first = true;
        foreach ($availCards as $code => $label) {
        ?>
            <div class="payzen-card">
            <?php if (count($availCards) === 1) {?>
                <input type="hidden" id="payzen_multi_card_type_<?php echo $code; ?>" name="payment[payzen_multi_cc_type]" value="<?php echo $code; ?>" disabled="disabled">
            <?php } else { ?>
                <input type="radio" class="radio" id="payzen_multi_card_type_<?php echo $code; ?>" name="payment[payzen_multi_cc_type]" value="<?php echo $code; ?>"<?php echo ($first ? ' checked="checked"' : ''); ?> disabled="disabled">
            <?php } ?>

                <label for="payzen_multi_card_type_<?php echo $code; ?>">
                    <img alt="<?php echo $label; ?>" src="<?php echo $this->getCcTypeImageSrc($code); ?>" title="<?php echo $label; ?>" />
                </label>

                <?php $first = false; ?>
            </div>
        <?php } ?>
        </div>
    </li>
    <?php endif; ?>
</ul>