<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display: none;">
    <?php $options = $this->getPaymentOptions(); ?>
    <li>
    <?php
        $first = true;
        foreach ($options as $code => $value) {
            $html = '<div class="payzen-option">';

            if (count($options) === 1) {
                $html .= '<input type="hidden" id="payzen_oney3x4x_option' . $code . '" value="' . $code . '" name="payment[payzen_oney3x4x_option]" disabled="disabled"><span style="margin-right: 20px;"></span>';
            } else {
                $html .= '<input type="radio"
                                 class="radio"
                                 id="payzen_oney3x4x_option' . $code . '"'.
                                 ($first ? ' checked="checked"' : '').'
                                 value="' . $code . '"
                                 name="payment[payzen_oney3x4x_option]"
                                 onclick="$$(\'.payzen_oney3x4x_review\').invoke(\'hide\'); $(\'payzen_oney3x4x_review_' . $code . '\').show();"
                                 disabled="disabled">' ;
            }

            $html .= '<label for="payzen_oney3x4x_option' . $code . '">' . $value['label'] . '</label>';
            $html .= '</div>';

            $html .= $this->getHtmlReview($value, $code, $first, 'oney3x4x');
            $html .= '<br style="margin-bottom: 5px;"/>';

            $first = false;

            echo $html;
        }
    ?>
    </li>
</ul>