<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$optionDetails = $this->getOptionDetails();

$date = time();
?>

<table class="payzen_fullcb_review payzen_review" style="padding : 15px;<?php echo (! $this->getFirst() ? ' display: none;' : ''); ?>" id="payzen_fullcb_review_<?php echo $optionDetails->getOptionCode(); ?>">
    <tbody>
        <tr>
            <td>
                <table>
                    <tbody>
                        <tr>
                            <td><?php echo Mage::helper('payzen')->__('Order amount :'); ?></td>
                            <td><strong><?php echo $optionDetails->getOrderTotal(); ?></strong></td>
                        </tr>
                        <tr>
                            <td><?php echo Mage::helper('payzen')->__('Fees :'); ?></td>
                            <td><strong><?php echo $optionDetails->getFundingFees(); ?></strong></td>
                        </tr>
                        <tr>
                            <td colspan="2"><hr style="margin: 0px;" /></td>
                        </tr>
                        <tr>
                            <td><?php echo Mage::helper('payzen')->__('Total amount :'); ?></td>
                            <td><strong><?php echo $optionDetails->getFundingTotal(); ?></strong></td>
                        </tr>
                    </tbody>
                </table>
            </td>

            <td>
                <table>
                    <tbody>
                        <tr>
                            <th colspan="2"><strong><?php echo Mage::helper('payzen')->__('Installments'); ?></strong></th>
                        </tr>
                        <tr>
                            <td><?php echo Mage::helper('core')->formatDate(date('Y-m-d', $date)); ?></td>
                            <td><strong><?php echo $optionDetails->getFirstPayment(); ?></strong></td>
                        </tr>
                        <?php
                        $count = $optionDetails->getCount();
                        for ($i=1; $i <= $count; $i++) {
                            $date = strtotime('+30 days', $date);
                        ?>
                        <tr>
                            <td><?php echo Mage::helper('core')->formatDate(date('Y-m-d', $date)); ?></td>
                            <td><strong><?php echo $optionDetails->getMonthlyPayment(); ?></strong></td>
                        </tr>
                        <?php
                        }
                        ?>
                   </tbody>
                </table>
           </td>
       </tr>
    </tbody>
</table>