<?php
/**
 * PayZen V2-Payment Module version 1.9.1 for Magento 1.4-1.9. Support contact : support@payzen.eu.
 *
 * NOTICE OF LICENSE
 *
 * This source file is licensed under the Open Software License version 3.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @author    Lyra Network (http://www.lyra-network.com/)
 * @copyright 2014-2018 Lyra Network and contributors
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @category  payment
 * @package   payzen
 */
?>

<?php if (Mage::getModel('payzen/payment_standard')->isOneclickAvailable()) : ?>
    <script type="text/javascript">
    //<![CDATA[
        var payzenUpdatePaymentBlock = function(blockName) {
            $$('ul#payment_form_payzen_standard li').invoke('hide');
            $$('ul#payment_form_payzen_standard li input').invoke('disable');
            $$('ul#payment_form_payzen_standard li select').invoke('disable');

            $$('li.payzen-standard-' + blockName + '-block').invoke('show');
            $$('li.payzen-standard-' + blockName + '-block input').invoke('enable');
            $$('li.payzen-standard-' + blockName + '-block select').invoke('enable');
        };

        var onMethodPayzenStandardClick = function(event) {
            payzenUpdatePaymentBlock.delay(0.2, 'id');
        };

        var payzenUpdateShippingBlock = function(event) {
            var form, params = {};

            var target = event.element();
            if (target) {
                form = $(target).up('form');
            }

            if (!form) {
                form = $('product_addtocart_form');
            }

            var validator  = new Validation(form, {stopOnFirst: true});

            if (! form || ! validator.validate()) {
                // invalid form data
                return;
            }

            form.getElements().each(function(elt) {
                if (elt.name) {
                    params[elt.name] = elt.value;
                }
            });

            new Ajax.Request("<?php echo $this->getUrl('payzen/payment/oneclickShipping', array('_secure' => true)) ?>", {
                method: 'post',
                parameters: params,
                onLoading: function(){
                    $$('#' + form.id + ' .payzen-please-wait').invoke('show');
                    $$('#' + form.id + ' .payzen-shipping-method').invoke('hide');
                },
                onSuccess: function(transport) {
                    $$('#' + form.id + ' .payzen-please-wait').invoke('hide');
                    $$('#' + form.id + ' .payzen-shipping-method').invoke('show');

                    var response = transport.responseText.evalJSON();
                    if (response.error) {
                        alert(response.message);
                    }

                    if (response.html) {
                        $$('#' + form.id + ' .shipping_method').first().update(response.html);
                    }
                }
            });
        };

        var payzenProductOneclickPayment = function(button) {
            var form = $('product_addtocart_form');
            var validator  = new Validation(form);

            if (! form || ! validator.validate()) {
                // invalid form data
                return;
            }

            var elts = $$('#' + form.id + ' .payzen-method-select');
            if (! elts || ! elts.length || ! elts.first().value) {
                return;
            }

            if (button) {
                button.disabled = true;
            }

            // override form action with PayZen 1-Click payment URL
            form.action = "<?php echo $this->getUrl('payzen/payment/oneclickPayment', array('_secure' => true)) ?>";
            form.submit();
        };
    //]]>
    </script>
<?php endif;?>