<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */

$product = $this->getProduct();
$buttonTitle = $this->getConfigData('one_click_title') ? $this->getConfigData('one_click_title') : Mage::helper('payzen')->__('Buy now');

if ($product->isSaleable() && $this->isOneclickAvailable()) :
?>
    <script type="text/javascript">
    //<![CDATA[
        var payzenOneclickInsert = function () {
            var btnHtml = '<button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="payzenProductOneclickPayment(this);" style="width: auto;">' +
                          '  <span><span><?php echo $buttonTitle ?></span></span>' +
                          '</button>';

            <?php if (version_compare(Mage::getVersion(), '1.9.0.0', '>=')) : ?>
                btnHtml = '<div class="add-to-cart-buttons">' + btnHtml + '</div>';
            <?php endif; ?>

            <?php if ($product->isVirtual()) : ?>
                <?php if (version_compare(Mage::getVersion(), '1.9.0.0', '<')) : ?>
                    btnHtml = btnHtml.replace('style="width: auto;"', 'style="width: auto; margin-left: 7px;"')
                <?php endif; ?>
                $$('.add-to-cart').first().insert(btnHtml);
            <?php else : ?>
                $$('.add-to-cart').first().insert({
                    after : '<div class="add-to-cart" style="float: left; margin: 10px 0;">' +
                            <?php echo Mage::helper('core')->jsonEncode($this->getChildHtml('payzen_shipping')); ?> +
                            btnHtml +
                            '</div>'
                });
            <?php endif; ?>
        };

        document.observe('dom:loaded', function() {
            payzenOneclickInsert.defer();

            if (typeof spConfig != 'undefined') {
                // Override Product.Config to fire option:change event.
                spConfig.reloadPrice = function() {
                    $$('.price').invoke('fire', 'option:change');
                    return Product.Config.prototype.reloadPrice.call(this);
                };
            }

            if (typeof opConfig != 'undefined') {
                // Override Product.Options to fire option:change event.
                opConfig.reloadPrice = function() {
                    $$('.price').invoke('fire', 'option:change');
                    return Product.Options.prototype.reloadPrice.call(this);
                };
            }

            // If selected option changes, update shipping methods.
            Event.observe($$('.price').first(), 'option:change', payzenUpdateShippingBlock);

            // If product quantity changes, update shipping methods.
            Event.observe($('qty'), 'change', payzenUpdateShippingBlock);

            // If any related product is checked or unchecked, update shipping methods.
            if ($$('.related-checkbox').length) {
                $$('.related-checkbox').each(function(elem) {
                    Event.observe(elem, 'change', payzenUpdateShippingBlock);
                });
            }

            if ($$('.block-related .block-subtitle a').length) {
                Event.observe($$('.block-related .block-subtitle a').first(), 'click', payzenUpdateShippingBlock);
            }
        });
    //]]>
    </script>
<?php endif; ?>