<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<ul class="payzen-form-list" style="text-align: left;">
    <li style="margin: 0 0 8px;">
        <?php echo $this->getChildHtml('payzen_oneclick_shipping_address'); ?>
    </li>

    <li class="shipping_method" style="margin: 0 0 8px;">
        <?php echo $this->getChildHtml('payzen_oneclick_shipping_method'); ?>
    </li>
</ul>