<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<html>
    <head>
    </head>

    <body>
        <?php echo $this->getLoaderHtml(); ?>

        <script type="text/javascript">
            if (window.top) {
                window.top.location = "<?php echo $this->getForwardUrl(); ?>";
            } else {
                window.location = "<?php echo $this->getForwardUrl(); ?>";
            }
        </script>
    </body>
</html>