<?php
/**
 * PayZen V2-Payment Module version 2.1.3 for Magento 2.x. Support contact : support@payzen.eu.
 *
 * NOTICE OF LICENSE
 *
 * This source file is licensed under the Open Software License version 3.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @author    Lyra Network (http://www.lyra-network.com/)
 * @copyright 2014-2017 Lyra Network and contributors
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @category  payment
 * @package   payzen
 */
?>

<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
          style="display:none">
    <?php
    $options = $block->getAvailableOptions();
    if (count($options) == 1) {
        $keys = array_keys($options);

        $key = $keys[0]; // the option key is the first array key
        $option = $options[$key]; // the option
    ?>
        <div class="admin__field" style="margin-bottom: 1rem !important; margin-top: 1rem !important;">
            <div class="admin__field-control">
                <input type="hidden"
                       id="option<?php echo $block->escapeHtml($key); ?>"
                       value="<?php echo $block->escapeHtml($key); ?>"
                       name="payment[payzen_multi_option]" disabled="disabled" />
                <label class="admin__field-label"><?php echo $block->escapeHtml($option['label']); ?></label>
            </div>
        </div>
    <?php
    } else {
        $first = true;
        foreach ($options as $key => $option) {
    ?>
            <div class="admin__field" style="margin-bottom: 1rem !important; margin-top: 1rem !important;">
                <div class="admin__field-control">
                    <input class="admin__control-radio validate-one-required-by-name"
                           type="radio"
                           id="option<?php echo $block->escapeHtml($key); ?>"
                           value="<?php echo $block->escapeHtml($key); ?>"
                           name="payment[payzen_multi_option]"
                           disabled="disabled"
                           <?php echo ($first == true ? ' checked="checked"' : ''); ?> />
                    <label for="option<?php echo $block->escapeHtml($key); ?>"
                           class="admin__field-label"><?php echo $block->escapeHtml($option['label']); ?></label>
                </div>
            </div>
    <?php
            $first = false;
        }
    }
    ?>
</fieldset>