<?php
/**
 * Copyright © Lyra Network.
 * This file is part of PayZen plugin for Magento 2. See COPYING.md for license details.
 *
 * @author    Lyra Network (https://www.lyra.com/)
 * @copyright Lyra Network
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<fieldset class="admin__fieldset payment-method"
          id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()); ?>"
          style="display: none;">
    <?php
    $options = $block->getAvailableOptions();
    if (count($options) === 1) {
        $keys = array_keys($options);

        $key = $keys[0]; // The option key is the first array key.
        $option = $options[$key]; // The option.
    ?>
        <div class="admin__field" style="margin-bottom: 1rem !important; margin-top: 1rem !important;">
            <div class="admin__field-control">
                <input type="hidden"
                       id="option<?php echo $block->escapeHtml($key); ?>"
                       value="<?php echo $block->escapeHtml($key); ?>"
                       name="payment[payzen_multi_option]" disabled="disabled" />
                <label class="admin__field-label"><?php echo $block->escapeHtml($option['label']); ?></label>
            </div>
        </div>
    <?php
    } else {
        $first = true;
        foreach ($options as $key => $option) {
    ?>
            <div class="admin__field" style="margin-bottom: 1rem !important; margin-top: 1rem !important;">
                <div class="admin__field-control">
                    <input class="admin__control-radio validate-one-required-by-name"
                           type="radio"
                           id="option<?php echo $block->escapeHtml($key); ?>"
                           value="<?php echo $block->escapeHtml($key); ?>"
                           name="payment[payzen_multi_option]"
                           disabled="disabled"
                           <?php echo ($first ? ' checked="checked"' : ''); ?> />
                    <label for="option<?php echo $block->escapeHtml($key); ?>"
                           class="admin__field-label"><?php echo $block->escapeHtml($option['label']); ?></label>
                </div>
            </div>
    <?php
            $first = false;
        }
    }
    ?>
</fieldset>